CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE obras (
    "Id" uuid NOT NULL,
    "Nome" character varying(160) NOT NULL,
    "Descricao" character varying(1000),
    "Endereco" character varying(500),
    "DataInicio" date NOT NULL,
    "DataPrevistaConclusao" date,
    "Status" integer NOT NULL,
    "SaldoAtual" numeric(18,2) NOT NULL,
    "DataEncerramento" timestamp with time zone,
    CONSTRAINT "PK_obras" PRIMARY KEY ("Id")
);

CREATE TABLE roles (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_roles" PRIMARY KEY ("Id")
);

CREATE TABLE socios (
    "Id" uuid NOT NULL,
    "Nome" character varying(160) NOT NULL,
    "Documento" character varying(32),
    "Email" character varying(160),
    "Telefone" character varying(40),
    "Ativo" boolean NOT NULL,
    CONSTRAINT "PK_socios" PRIMARY KEY ("Id")
);

CREATE TABLE users (
    "Id" uuid NOT NULL,
    "Nome" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id")
);

CREATE TABLE encerramentos_obra (
    "Id" uuid NOT NULL,
    "ObraId" uuid NOT NULL,
    "TotalInvestido" numeric(18,2) NOT NULL,
    "TotalGasto" numeric(18,2) NOT NULL,
    "TotalRecebido" numeric(18,2) NOT NULL,
    "ValorPermutasEstimado" numeric(18,2) NOT NULL,
    "ResultadoFinanceiro" numeric(18,2) NOT NULL,
    "DataEncerramento" timestamp with time zone NOT NULL,
    "Observacao" character varying(1000),
    CONSTRAINT "PK_encerramentos_obra" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_encerramentos_obra_obras_ObraId" FOREIGN KEY ("ObraId") REFERENCES obras ("Id") ON DELETE CASCADE
);

CREATE TABLE vendas (
    "Id" uuid NOT NULL,
    "ObraId" uuid NOT NULL,
    "Tipo" integer NOT NULL,
    "ValorTotalNegociado" numeric(18,2) NOT NULL,
    "ValorEntrada" numeric(18,2) NOT NULL,
    "DataVenda" date NOT NULL,
    "CompradorNome" character varying(160) NOT NULL,
    "CompradorDocumento" character varying(32),
    "Observacao" character varying(1000),
    "Status" integer NOT NULL,
    CONSTRAINT "PK_vendas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_vendas_obras_ObraId" FOREIGN KEY ("ObraId") REFERENCES obras ("Id") ON DELETE CASCADE
);

CREATE TABLE role_claims (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_role_claims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_role_claims_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES roles ("Id") ON DELETE CASCADE
);

CREATE TABLE movimentacoes_financeiras (
    "Id" uuid NOT NULL,
    "ObraId" uuid NOT NULL,
    "Tipo" integer NOT NULL,
    "Categoria" character varying(80) NOT NULL,
    "Valor" numeric(18,2) NOT NULL,
    "DataMovimentacao" date NOT NULL,
    "Descricao" character varying(500) NOT NULL,
    "SocioId" uuid,
    "ParcelaReceberId" uuid,
    "Status" integer NOT NULL,
    "CriadoEm" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_movimentacoes_financeiras" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_movimentacoes_financeiras_obras_ObraId" FOREIGN KEY ("ObraId") REFERENCES obras ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_movimentacoes_financeiras_socios_SocioId" FOREIGN KEY ("SocioId") REFERENCES socios ("Id") ON DELETE RESTRICT
);

CREATE TABLE obra_socios (
    "Id" uuid NOT NULL,
    "ObraId" uuid NOT NULL,
    "SocioId" uuid NOT NULL,
    "PercentualParticipacao" numeric(5,2) NOT NULL,
    "Observacao" character varying(500),
    CONSTRAINT "PK_obra_socios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_obra_socios_obras_ObraId" FOREIGN KEY ("ObraId") REFERENCES obras ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_obra_socios_socios_SocioId" FOREIGN KEY ("SocioId") REFERENCES socios ("Id") ON DELETE RESTRICT
);

CREATE TABLE user_claims (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_user_claims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_user_claims_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE user_logins (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_user_logins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_user_logins_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE user_roles (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_user_roles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_user_roles_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES roles ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_user_roles_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE user_tokens (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_user_tokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_user_tokens_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE distribuicoes_resultado (
    "Id" uuid NOT NULL,
    "EncerramentoObraId" uuid NOT NULL,
    "SocioId" uuid NOT NULL,
    "PercentualParticipacao" numeric(5,2) NOT NULL,
    "ValorInvestido" numeric(18,2) NOT NULL,
    "ValorResultado" numeric(18,2) NOT NULL,
    "ValorAReceberOuPagar" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_distribuicoes_resultado" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_distribuicoes_resultado_encerramentos_obra_EncerramentoObra~" FOREIGN KEY ("EncerramentoObraId") REFERENCES encerramentos_obra ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_distribuicoes_resultado_socios_SocioId" FOREIGN KEY ("SocioId") REFERENCES socios ("Id") ON DELETE RESTRICT
);

CREATE TABLE ativos_permuta (
    "Id" uuid NOT NULL,
    "VendaId" uuid NOT NULL,
    "ObraId" uuid NOT NULL,
    "Tipo" integer NOT NULL,
    "Descricao" character varying(500) NOT NULL,
    "ValorEstimado" numeric(18,2) NOT NULL,
    "DocumentoReferencia" character varying(120),
    "DataRecebimento" date NOT NULL,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_ativos_permuta" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ativos_permuta_obras_ObraId" FOREIGN KEY ("ObraId") REFERENCES obras ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ativos_permuta_vendas_VendaId" FOREIGN KEY ("VendaId") REFERENCES vendas ("Id") ON DELETE CASCADE
);

CREATE TABLE aportes (
    "Id" uuid NOT NULL,
    "ObraId" uuid NOT NULL,
    "SocioId" uuid NOT NULL,
    "MovimentacaoFinanceiraId" uuid NOT NULL,
    "Valor" numeric(18,2) NOT NULL,
    "DataAporte" date NOT NULL,
    CONSTRAINT "PK_aportes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_aportes_movimentacoes_financeiras_MovimentacaoFinanceiraId" FOREIGN KEY ("MovimentacaoFinanceiraId") REFERENCES movimentacoes_financeiras ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_aportes_obras_ObraId" FOREIGN KEY ("ObraId") REFERENCES obras ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_aportes_socios_SocioId" FOREIGN KEY ("SocioId") REFERENCES socios ("Id") ON DELETE RESTRICT
);

CREATE TABLE despesas (
    "Id" uuid NOT NULL,
    "ObraId" uuid NOT NULL,
    "MovimentacaoFinanceiraId" uuid NOT NULL,
    "Categoria" integer NOT NULL,
    "Fornecedor" character varying(160),
    "DocumentoFiscal" character varying(80),
    CONSTRAINT "PK_despesas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_despesas_movimentacoes_financeiras_MovimentacaoFinanceiraId" FOREIGN KEY ("MovimentacaoFinanceiraId") REFERENCES movimentacoes_financeiras ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_despesas_obras_ObraId" FOREIGN KEY ("ObraId") REFERENCES obras ("Id") ON DELETE CASCADE
);

CREATE TABLE parcelas_receber (
    "Id" uuid NOT NULL,
    "VendaId" uuid NOT NULL,
    "ObraId" uuid NOT NULL,
    "Numero" integer NOT NULL,
    "Valor" numeric(18,2) NOT NULL,
    "DataVencimento" date NOT NULL,
    "DataPagamento" date,
    "Status" integer NOT NULL,
    "MovimentacaoFinanceiraId" uuid,
    CONSTRAINT "PK_parcelas_receber" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_parcelas_receber_movimentacoes_financeiras_MovimentacaoFina~" FOREIGN KEY ("MovimentacaoFinanceiraId") REFERENCES movimentacoes_financeiras ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_parcelas_receber_obras_ObraId" FOREIGN KEY ("ObraId") REFERENCES obras ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_parcelas_receber_vendas_VendaId" FOREIGN KEY ("VendaId") REFERENCES vendas ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_aportes_MovimentacaoFinanceiraId" ON aportes ("MovimentacaoFinanceiraId");

CREATE INDEX "IX_aportes_ObraId" ON aportes ("ObraId");

CREATE INDEX "IX_aportes_SocioId" ON aportes ("SocioId");

CREATE INDEX "IX_ativos_permuta_ObraId_Status" ON ativos_permuta ("ObraId", "Status");

CREATE INDEX "IX_ativos_permuta_VendaId" ON ativos_permuta ("VendaId");

CREATE INDEX "IX_despesas_MovimentacaoFinanceiraId" ON despesas ("MovimentacaoFinanceiraId");

CREATE INDEX "IX_despesas_ObraId" ON despesas ("ObraId");

CREATE INDEX "IX_distribuicoes_resultado_EncerramentoObraId" ON distribuicoes_resultado ("EncerramentoObraId");

CREATE INDEX "IX_distribuicoes_resultado_SocioId" ON distribuicoes_resultado ("SocioId");

CREATE UNIQUE INDEX "IX_encerramentos_obra_ObraId" ON encerramentos_obra ("ObraId");

CREATE INDEX "IX_movimentacoes_financeiras_ObraId_DataMovimentacao" ON movimentacoes_financeiras ("ObraId", "DataMovimentacao");

CREATE INDEX "IX_movimentacoes_financeiras_ObraId_Tipo" ON movimentacoes_financeiras ("ObraId", "Tipo");

CREATE INDEX "IX_movimentacoes_financeiras_SocioId" ON movimentacoes_financeiras ("SocioId");

CREATE UNIQUE INDEX "IX_obra_socios_ObraId_SocioId" ON obra_socios ("ObraId", "SocioId");

CREATE INDEX "IX_obra_socios_SocioId" ON obra_socios ("SocioId");

CREATE INDEX "IX_obras_Status" ON obras ("Status");

CREATE UNIQUE INDEX "IX_parcelas_receber_MovimentacaoFinanceiraId" ON parcelas_receber ("MovimentacaoFinanceiraId");

CREATE INDEX "IX_parcelas_receber_ObraId_Status_DataVencimento" ON parcelas_receber ("ObraId", "Status", "DataVencimento");

CREATE INDEX "IX_parcelas_receber_VendaId" ON parcelas_receber ("VendaId");

CREATE INDEX "IX_role_claims_RoleId" ON role_claims ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON roles ("NormalizedName");

CREATE INDEX "IX_user_claims_UserId" ON user_claims ("UserId");

CREATE INDEX "IX_user_logins_UserId" ON user_logins ("UserId");

CREATE INDEX "IX_user_roles_RoleId" ON user_roles ("RoleId");

CREATE INDEX "EmailIndex" ON users ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON users ("NormalizedUserName");

CREATE UNIQUE INDEX "IX_vendas_ObraId" ON vendas ("ObraId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260601122352_InitialCreate', '8.0.6');

COMMIT;

START TRANSACTION;

CREATE TABLE fornecedores (
    "Id" uuid NOT NULL,
    "Nome" character varying(160) NOT NULL,
    "Documento" character varying(32),
    "Telefone" character varying(40),
    "Ativo" boolean NOT NULL,
    CONSTRAINT "PK_fornecedores" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_fornecedores_Nome" ON fornecedores ("Nome");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260602110153_AddFornecedores', '8.0.6');

COMMIT;

